In [1]:
# p52
# ReLU関数
import numpy as np
def relu(x):
    return np.maximum(0,x)

# sigmoid関数
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [4]:
# テスト用
t1 = np.array([-1,0,1,2,3,4,5,6])
t2 = np.array([[-2,1,-5,3],[2,-0.5,1,2]])
t3 = np.array([[1],[0],[0],[1]])
t4 = np.array([[1,0,0,1],[1,0,0,1]])

print(relu(t2))
print(np.ndim(t2)) # 次元数
print(t2.shape) # サイズ
print(np.dot(t2,t3)) # 行列の積
print(t2*t4)

In [9]:
# 恒等写像
def identity_function(x):
    return x

In [10]:
# p61
X = np.array([1.0,0.5])
W1 = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
B1 = np.array([0.1,0.2,0.3])
A1 = np.dot(X, W1) + B1
Z1 = sigmoid(A1)
print(A1)
print(Z1)

W2 = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
B2 = np.array([0.1,0.2])
A2 = np.dot(Z1,W2)+B2
Z2 = sigmoid(A2)

W3 = np.array([[0.1,0.3],[0.2,0.4]])
B3 = np.array([0.1,0.2])
A3 = np.dot(Z2,W3)+B3
Y = identity_function(A3)

[ 0.3  0.7  1.1]
[ 0.57444252  0.66818777  0.75026011]


In [11]:
# p65
def init_network():
    network = {}
    network['W1'] = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
    network['b1'] = np.array([0.1,0.2,0.3])
    network['W2'] = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
    network['b2'] = np.array([0.1,0.2])
    network['W3'] = np.array([[0.1,0.3],[0.2,0.4]])
    network['b3'] = np.array([0.1,0.2])
    print(network['W1'])
    return network


def forward(network,x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = identity_function(a3)
    return y

In [12]:
network = init_network()
x = np.array([1.0,0.5])
y = forward(network, x)
print(y) #[0.31682708 0.69627909]

[[ 0.1  0.3  0.5]
 [ 0.2  0.4  0.6]]
[ 0.31682708  0.69627909]


In [20]:
# ソフトマックスでオーバーフローが発生する例
def softmax_old(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [21]:
a = np.array([1010,1000,990])
np.exp(a)/np.sum(np.exp(a))

c = np.max(a) # 1010
a - c
np.exp(a-c)/np.sum(np.exp(a-c)) # array([  9.99954600e-01,   4.53978686e-05,   2.06106005e-09])

c:\users\haruta\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  
c:\users\haruta\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([  9.99954600e-01,   4.53978686e-05,   2.06106005e-09])

In [22]:
# ソフトマックスでオーバーフローを防ぐための工夫
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a-c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [23]:
a = np.array([0.3,2.9,4.0])
y = softmax(a)
print(y) # [ 0.01821127  0.24519181  0.73659691]
print(np.sum(y))

[ 0.01821127  0.24519181  0.73659691]
1.0
